### PR TITLE
Emit a descriptive error when running the generator on iOS, tvOS, or watchOS

### LINKED ISSUE #86: Emit a descriptive error when running the generator on iOS, tvOS, or watchOS
The `_OpenAPIGeneratorCore` library and `swift-openapi-generator` executable are mostly an implementation detail of the `OpenAPIGenerator` plugin, all vended by the `swift-openapi-generator` package.

The generator runs at _build_ time to generate code, but the `_OpenAPIGeneratorCore` library shouldn't actually be linked by adopters's target, which is documented correctly here (Step 7 of https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.3/tutorials/swift-openapi-generator/clientxcode#Configuring-your-target-to-use-the-Swift-OpenAPI-Generator-plugin), but it's also easy to get it wrong and link it when adding the package in Xcode.

We should make it so that a clear, descriptive error is emitted when someone links the generator module itself to a non-macOS/Linux target.

### PR DESCRIPTION
**Pull request by czechboy0**
### Motivation

Resolves #86, which some adopters are hitting by accident.

### Modifications

Makes the generator itself build successfully on iOS, tvOS, watchOS, but not really, as I just added an explicit, clear error on those platforms pointing out that the adopter probably did this by accident, and how to fix it.

### Result

A clear, descriptive error is now emitted when the adopter links the `_OpenAPIGeneratorCore` target from e.g. an iOS app (most likely by accident):

```
.../swift-openapi-generator/Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:4:8 Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift-openapi-generator/issues/86
```

### Test Plan

Tested locally by creating an iOS app with a lower deployment target and linked the generator directly. The error goes away when the linkages is removed, as expected.

### CODE REVIEW

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift [hunk 1]
```diff
@@ -0,0 +1,5 @@
+
+// Details: https://github.com/apple/swift-openapi-generator/issues/86
+#if os(iOS) || os(tvOS) || os(watchOS)
+#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift-openapi-generator/issues/86")
```
Comment (czechboy0) [inline Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:4]: Feedback on the wording is welcome.

Comment (denil-ct) [reply Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:17]: _The generator tool cannot run on iOS, tvOS, or watchOS. Make sure your app does not link against the generator directly. See https://github.com/apple/swift-openapi-generator/issues/86 for details._

I feel like this removes redundant words from the first sentence and on the second, it adds a more polite and imperative tone.

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+//
+// See LICENSE.txt for license information
+// See CONTRIBUTORS.txt for the list of SwiftOpenAPIGenerator project authors
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+//===----------------------------------------------------------------------===//
+
+// Details: https://github.com/apple/swift-openapi-generator/issues/86
+#if os(iOS) || os(tvOS) || os(watchOS)
```
Comment (simonjbeaumont) [inline Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:16]: I think this is what we want. Especially with upcoming `visionOS`.

```suggestion
#if !os(macOS) || !os(Linux)
```

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+// Licensed under Apache License v2.0
+//
+// See LICENSE.txt for license information
+// See CONTRIBUTORS.txt for the list of SwiftOpenAPIGenerator project authors
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+//===----------------------------------------------------------------------===//
+
+// Details: https://github.com/apple/swift-openapi-generator/issues/86
```
Comment (simonjbeaumont) [inline Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:15]: I'd rather us carry informative comments _here_ than link out to Github.

```suggestion
// Emit a compiler error if this library is linked with a target in an adopter project.
```

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+#if os(iOS) || os(tvOS) || os(watchOS)
+#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift-openapi-generator/issues/86")
```
Comment (simonjbeaumont) [inline Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:17]:
```suggestion
#error("_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library directly.")
```

File: Package.swift [hunk 5]
```diff
@@ -17,7 +17,13 @@ import PackageDescription
...
     name: "swift-openapi-generator",
     platforms: [
-        .macOS(.v10_15)
+        .macOS(.v10_15),
+
+        // The platforms below are not currently supported for running the
+        // generator itself (only the generated code), they are here
+        // to allow the generator to emit a more descriptive error,
+        // see the file PlatformChecks.swift for details.
+        .iOS(.v13), .tvOS(.v13), .watchOS(.v6),
```
Comment (simonjbeaumont) [inline Package.swift:26]: I'm really not a fan of us having to do this and would rather us consider removing `_OpenAPIGeneratorCore` from `products`.

If we do have to do it, we can make use of string version numbers for unreasonably high version numbers, e.g.

```suggestion
        .macOS(.v10_15),

        // The platforms below are not currently supported for running the generator itself.
        // We include them here to allow the us to emit a more descriptive compiler error.
        .iOS("99"), .tvOS("99"), .watchOS("99"),
```

**Review by simonjbeaumont — CHANGES_REQUESTED** [review]
If we removed `_OpenAPIGeneratorCore` from the `products` then I think this is less likely to trip folks up. When I tested that approach locally, it is no longer offered by Xcode when adding the package dependency.

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift (hunk 4 above)
Comment (czechboy0) [reply Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:17]: They might have linked the CLI though, not the Core library, so it might be confusing why we're warning about the library.

File: Package.swift (hunk 5 above)
Comment (czechboy0) [reply Package.swift:26]: I'll do the high version numbers, are 9999 instead also good? I've seen that used elsewhere.

Comment (simonjbeaumont) [reply Package.swift:26]: While they work in `@available` annotations, I tried them in this setting and it caused less readable errors because there are some other macro expansions which seem to rely on the major component being 2 digits. You can try and see for yourself what happens if you use 9999.

File: Sources/_OpenAPIGeneratorCore/PlatformChecks.swift (hunk 4 above)
Comment (simonjbeaumont) [reply Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:17]: OK, well we can append a little to the message?

```suggestion
#error("_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library or the plugin directly.")
```
