### PR TITLE
Generate arrays with an optional element type for arrays with nullable items

### LINKED ISSUE #444: Support generating nullable array elements
Error: 
```
Client error - cause description: 'Unknown', underlying error: DecodingError: valueNotFound Double
```
```
Cannot get unkeyed decoding container -- found null value instead (underlying error: <nil>)
```

openapi.yaml
```
openapi: 3.0.3
info:
  title: MyService
  version: 1.0.0
servers:
  - url: 'https://api.myservice.com'
    description: myservice
paths:
  '/data/{id}':
    get:
      operationId: data
      parameters:
        - name: id
          required: true
          in: path
          description: The id.
          schema:
            type: string
      responses:
        '200':
          description: A success response with a MyData.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyData'
components:
  schemas:
    MyData:
      type: object
      required: []
      properties:
        points:
          type: object
          required: []
          properties:
            result:
              type: array
              items:
                type: object
                required: []
                properties:
                  one:
                    type: array
                    items:
                      type: number
                      nullable: true
```
```
% sw_vers                                                       
ProductName:        macOS
ProductVersion:     14.1.2
BuildVersion:       23B92
```
My schema requires that the type of array's items (numbers) need to be nullable (or `nil`).

### PR DESCRIPTION
**Pull request by simonjbeaumont**
### Motivation

Array items can be nullable. When this is the case, the element type of the generated array should be optional. Today it is not. For example, consider the following OpenAPI snippet:

```yaml
  StringArrayNullableItems:
    type: array
    items:
      type: [string, null]
```

This currently generates a type alias for `[String]` but it should be `[String?]`

### Modifications

Update the translator to take into account `arrayContext.items.nullable` when generating the types for array values.

### Result

Arrays with nullable items 

### Test Plan

- Snippet test for standalone schema.
- Snippet test for use within an object.
- A test that shows lossless conversion to JSON with Foundation.

### Related issues

- Fixes #444.

### CODE REVIEW

File: Sources/_OpenAPIGeneratorCore/Translator/CommonTranslations/translateArray.swift [hunk 1]
```diff
@@ -48,6 +48,7 @@ extension TypesFileTranslator {
                 let nestedDecls = try translateSchema(typeName: elementType.typeName, schema: items, overrides: .none)
                 inline.append(contentsOf: nestedDecls)
             }
+            if items.nullable { elementType = elementType.asOptional }
```
Comment (czechboy0) [inline Sources/_OpenAPIGeneratorCore/Translator/CommonTranslations/translateArray.swift:51]: Please remove this one.

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Just the one change can be undone, otherwise looks great

**Review by czechboy0 — APPROVED** [review]
