### PR TITLE
Eliminate unreachable default branch in Output accessors for default-only responses

### LINKED ISSUE #810: Generated code for operation with default-only response has compiler warning 'Default will never be executed'
### Description

When an openapi spec operation has a responses object containing only a `default` field:
https://spec.openapis.org/oas/v3.1.1.html#fixed-fields-13
the generated code for that operation triggers a compiler warning.

The spec's aren't crystal clear on whether that is allowed:
https://spec.openapis.org/oas/v3.1.1.html#responses-object
https://spec.openapis.org/oas/v3.0.4.html#responses-object
Redocly CLI lint (a popular validation tool) accepts it though, and it seems a useful declaration for an operation that only ever performs a redirect.

### Reproduction

```yaml
# openapi.yaml
openapi: 3.0.4
info:
  title: My API
  version: 0.0.1
paths:
  /authorize:
    get:
      operationId: authorize
      summary: Initiate OpenID Connect (OIDC) login
      security: []
      responses:
        default:
          description: A redirect to the OIDC provider.
```

```yaml
# openapi-generator-config.yaml
generate:
  - types
  - client
accessModifier: package
namingStrategy: idiomatic
```

```swift
# Types.swift
    package enum Authorize {
        package static let id: Swift.String = "authorize"
        package struct Input: Sendable, Hashable {
            /// Creates a new `Input`.
            package init() {}
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Default: Sendable, Hashable {
                /// Creates a new `Default`.
                package init() {}
            }
            /// A redirect to the OIDC provider.
            ///
            /// - Remark: Generated from `#/paths//authorize/get(authorize)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.Authorize.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            package var `default`: Operations.Authorize.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default: // <----------- WARNING: "Default will never be executed"
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
    }
```

### Package version(s)

```
    {
      "identity" : "swift-openapi-generator",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-openapi-generator",
      "state" : {
        "revision" : "bb9a13596af11db9bb83389295d91cd335810fe8",
        "version" : "1.10.2"
      }
    },
    {
      "identity" : "swift-openapi-runtime",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-openapi-runtime",
      "state" : {
        "revision" : "8f33cc5dfe81169fb167da73584b9c72c3e8bc23",
        "version" : "1.8.2"
      }
    },
    {
      "identity" : "swift-openapi-urlsession",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-openapi-urlsession",
      "state" : {
        "revision" : "6fac6f7c428d5feea2639b5f5c8b06ddfb79434b",
        "version" : "1.1.0"
      }
    },
```

### Expected behavior

Generated code never triggers a compiler warning

### Environment

```console
swift -version
swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alxxndrv**
### Motivation
OpenAPI operations that declare only a default response caused the generator to emit an accessor switch with an extra fallback branch that is statically unreachable, triggering a Swift compiler warning: `Default will never be executed.` The OpenAPI spec explicitly allows default as the only entry in the Responses Object, and tooling validates such specs. This change ensures generated code is clean and warning-free for these valid definitions. Fixes #810.

### Result
For default-only outputs, the accessor is exhaustive and compiles without unreachable code warnings. Multi-case outputs are unchanged and continue to throw for mismatches. No changes to the public API surface or signatures of generated types

### Modifications
- Generator:
  - Updated the accessor generation to omit the fallback default branch when the Output enum is provably single-case (operation contains only default). Multi-case outputs retain the fallback that throws
  - Accessor signatures remain throwing for source compatibility
  - Change implemented in [Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift](Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift)
- Reference tests:
  - Adjusted the default-only accessor expectation to an exhaustive switch without a fallback default branch in [Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift](Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift)

### Result
- For default-only outputs, the accessor is exhaustive and compiles without unreachable code warnings
- Multi-case outputs are unchanged and continue to throw for mismatches
- No changes to the public API surface or signatures of generated types

### Test Plan
- Tests were modified to reflect the new accessor shape; additional checks needed

### Links
Fixes https://github.com/apple/swift-openapi-generator/issues/810, OpenAPI spec rule: https://spec.openapis.org/oas/v3.1.1.html#responses-object

### CODE REVIEW

File: Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift [hunk 1]
```diff
@@ -87,6 +87,39 @@ extension TypesFileTranslator {
...
+            SwitchCaseDescription(
+                kind: .case(
+                    .dot(responseKind.identifier),
+                    responseKind.wantsStatusCode ? ["_", "response"] : ["response"]
+                ),
+                body: [.expression(.return(.identifierPattern("response")))]
+            )
+        ]
+        if !isSingleCaseOutput {
+            throwingGetterCases.append(
```
Comment (czechboy0) [inline Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift:102]:
```suggestion
        var throwingGetterCases: [SwitchCaseDescription] = [
SwitchCaseDescription(
kind: .case(
.dot(responseKind.identifier),
responseKind.wantsStatusCode ? ["_", "response"] : ["response"]
),
body: [.expression(.return(.identifierPattern("response")))]
            )
        ]
        if !operation.containsDefaultResponse || operation.responseOutcomes.count > 1 {
            throwingGetterCases.append(
```

We can remove the local variable and just inline the check.

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Overall looks good, just one suggestion. Thanks @alxxndrv 🙏

**Comment by alxxndrv** [comment]
Thanks @czechboy0! 🙏 I've committed the suggested change.

**Comment by czechboy0** [comment]
@alxxndrv apologies about the delay - can you rerun the formatter? The CI still seems red

**Comment by alxxndrv** [comment]
@czechboy0 Got it—thanks for the heads-up! I’ve re-run the formatter; should be good to go now
